from __future__ import annotations

import unicodedata
from typing import Iterable

GENERAL_REPLACEMENTS = (
    ("\ufeff", ""),
    ("\u200b", ""),
    ("\u200c", ""),
    ("\u200d", ""),
    ("\u2060", ""),
    ("\u00ad", ""),
    ("“", '"'),
    ("”", '"'),
    ("„", '"'),
    ("‟", '"'),
    ("‘", "'"),
    ("’", "'"),
    ("‚", "'"),
    ("‛", "'"),
    ("‐", "-"),
    ("‑", "-"),
    ("‒", "-"),
    ("–", "-"),
    ("—", "-"),
    ("―", "-"),
    ("…", "..."),
    ("·", "."),
    ("•", "*"),
    ("‧", "."),
    ("、", ","),
    ("。", "."),
    ("／", "/"),
    ("＼", "\\"),
    ("％", "%"),
    ("＆", "&"),
    ("＠", "@"),
    ("＃", "#"),
    ("＊", "*"),
    ("＋", "+"),
    ("＝", "="),
    ("＜", "<"),
    ("＞", ">"),
    ("｜", "|"),
    ("＾", "^"),
    ("｀", "`"),
    ("～", "~"),
    ("　", " "),
)

LATIN_REPLACEMENTS = (
    ("ß", "ss"),
    ("ẞ", "SS"),
    ("æ", "ae"),
    ("Æ", "AE"),
    ("œ", "oe"),
    ("Œ", "OE"),
    ("ø", "o"),
    ("Ø", "O"),
    ("ð", "d"),
    ("Ð", "D"),
    ("þ", "th"),
    ("Þ", "TH"),
    ("ł", "l"),
    ("Ł", "L"),
    ("đ", "d"),
    ("Đ", "D"),
    ("ĸ", "k"),
    ("ƒ", "f"),
    ("ĳ", "ij"),
    ("Ĳ", "IJ"),
    ("Ǉ", "LJ"),
    ("ǈ", "Lj"),
    ("ǉ", "lj"),
    ("Ǌ", "NJ"),
    ("ǋ", "Nj"),
    ("ǌ", "nj"),
    ("ﬀ", "ff"),
    ("ﬁ", "fi"),
    ("ﬂ", "fl"),
    ("ﬃ", "ffi"),
    ("ﬄ", "ffl"),
    ("ﬅ", "ft"),
    ("ﬆ", "st"),
    ("Á", "A"),
    ("À", "A"),
    ("Â", "A"),
    ("Ã", "A"),
    ("Ä", "A"),
    ("Å", "A"),
    ("Ā", "A"),
    ("Ă", "A"),
    ("Ą", "A"),
    ("Ç", "C"),
    ("Ć", "C"),
    ("Ĉ", "C"),
    ("Ċ", "C"),
    ("Č", "C"),
    ("É", "E"),
    ("È", "E"),
    ("Ê", "E"),
    ("Ë", "E"),
    ("Ē", "E"),
    ("Ė", "E"),
    ("Ę", "E"),
    ("Ě", "E"),
    ("Í", "I"),
    ("Ì", "I"),
    ("Î", "I"),
    ("Ï", "I"),
    ("Ĩ", "I"),
    ("Ī", "I"),
    ("İ", "I"),
    ("Ñ", "N"),
    ("Ń", "N"),
    ("Ň", "N"),
    ("Ó", "O"),
    ("Ò", "O"),
    ("Ô", "O"),
    ("Õ", "O"),
    ("Ö", "O"),
    ("Ő", "O"),
    ("Ō", "O"),
    ("Ú", "U"),
    ("Ù", "U"),
    ("Û", "U"),
    ("Ü", "U"),
    ("Ű", "U"),
    ("Ū", "U"),
    ("Ý", "Y"),
    ("Ÿ", "Y"),
    ("Ź", "Z"),
    ("Ż", "Z"),
    ("Ž", "Z"),
    ("🄐", "A"),
    ("🄑", "B"),
    ("🄒", "C"),
    ("🄓", "D"),
    ("🄔", "E"),
    ("🄕", "F"),
    ("🄖", "G"),
    ("🄗", "H"),
    ("🄘", "I"),
    ("🄙", "J"),
    ("🄚", "K"),
    ("🄛", "L"),
    ("🄜", "M"),
    ("🄝", "N"),
    ("🄞", "O"),
    ("🄟", "P"),
    ("🄠", "Q"),
    ("🄡", "R"),
    ("🄢", "S"),
    ("🄣", "T"),
    ("🄤", "U"),
    ("🄥", "V"),
    ("🄦", "W"),
    ("🄧", "X"),
    ("🄨", "Y"),
    ("🄩", "Z"),
    ("🅐", "A"),
    ("🅑", "B"),
    ("🅒", "C"),
    ("🅓", "D"),
    ("🅔", "E"),
    ("🅕", "F"),
    ("🅖", "G"),
    ("🅗", "H"),
    ("🅘", "I"),
    ("🅙", "J"),
    ("🅚", "K"),
    ("🅛", "L"),
    ("🅜", "M"),
    ("🅝", "N"),
    ("🅞", "O"),
    ("🅟", "P"),
    ("🅠", "Q"),
    ("🅡", "R"),
    ("🅢", "S"),
    ("🅣", "T"),
    ("🅤", "U"),
    ("🅥", "V"),
    ("🅦", "W"),
    ("🅧", "X"),
    ("🅨", "Y"),
    ("🅩", "Z"),
    ("🄰", "A"),
    ("🄱", "B"),
    ("🄲", "C"),
    ("🄳", "D"),
    ("🄴", "E"),
    ("🄵", "F"),
    ("🄶", "G"),
    ("🄷", "H"),
    ("🄸", "I"),
    ("🄹", "J"),
    ("🄺", "K"),
    ("🄻", "L"),
    ("🄼", "M"),
    ("🄽", "N"),
    ("🄾", "O"),
    ("🄿", "P"),
    ("🅀", "Q"),
    ("🅁", "R"),
    ("🅂", "S"),
    ("🅃", "T"),
    ("🅄", "U"),
    ("🅅", "V"),
    ("🅆", "W"),
    ("🅇", "X"),
    ("🅈", "Y"),
    ("🅉", "Z"),
    ("₳", "A"),
    ("฿", "B"),
    ("₵", "C"),
    ("Đ", "D"),
    ("Ɇ", "E"),
    ("₣", "F"),
    ("₲", "G"),
    ("Ⱨ", "H"),
    ("ł", "L"),
    ("₭", "K"),
    ("Ⱡ", "L"),
    ("₥", "M"),
    ("₦", "N"),
    ("Ø", "O"),
    ("₱", "P"),
    ("Ɽ", "R"),
    ("₴", "S"),
    ("₮", "T"),
    ("Ʉ", "U"),
    ("₩", "W"),
    ("Ӿ", "X"),
    ("Ɏ", "Y"),
    ("Ⱬ", "Z"),
    ("ʎ", "y"),
    ("ʍ", "w"),
    ("ʌ", "v"),
    ("ʇ", "t"),
    ("ʃ", "s"),
    ("ɹ", "r"),
    ("ɯ", "m"),
    ("ʞ", "k"),
    ("ɾ", "j"),
    ("ı", "i"),
    ("ɥ", "h"),
    ("ƃ", "g"),
    ("ɟ", "f"),
    ("ǝ", "e"),
    ("ɔ", "c"),
    ("ɐ", "a"),
)

GREEK_REPLACEMENTS = (
    ("α", "a"),
    ("β", "b"),
    ("γ", "g"),
    ("δ", "d"),
    ("ε", "e"),
    ("ζ", "z"),
    ("η", "h"),
    ("θ", "th"),
    ("ι", "i"),
    ("κ", "k"),
    ("λ", "l"),
    ("μ", "m"),
    ("ν", "n"),
    ("ξ", "x"),
    ("ο", "o"),
    ("π", "p"),
    ("ρ", "r"),
    ("ς", "s"),
    ("σ", "s"),
    ("τ", "t"),
    ("υ", "u"),
    ("φ", "f"),
    ("χ", "x"),
    ("ψ", "ps"),
    ("ω", "o"),
    ("Α", "A"),
    ("Β", "B"),
    ("Γ", "G"),
    ("Δ", "D"),
    ("Ε", "E"),
    ("Ζ", "Z"),
    ("Η", "H"),
    ("Θ", "TH"),
    ("Ι", "I"),
    ("Κ", "K"),
    ("Λ", "L"),
    ("Μ", "M"),
    ("Ν", "N"),
    ("Ξ", "X"),
    ("Ο", "O"),
    ("Π", "P"),
    ("Ρ", "R"),
    ("Σ", "S"),
    ("Τ", "T"),
    ("Υ", "Y"),
    ("Φ", "F"),
    ("Χ", "X"),
    ("Ψ", "PS"),
    ("Ω", "O"),
)

CYRILLIC_REPLACEMENTS = (
    ("а", "a"),
    ("б", "b"),
    ("в", "v"),
    ("г", "g"),
    ("д", "d"),
    ("е", "e"),
    ("ё", "e"),
    ("ж", "zh"),
    ("з", "z"),
    ("и", "i"),
    ("й", "i"),
    ("к", "k"),
    ("л", "l"),
    ("м", "m"),
    ("н", "n"),
    ("о", "o"),
    ("п", "p"),
    ("р", "r"),
    ("с", "s"),
    ("т", "t"),
    ("у", "u"),
    ("ф", "f"),
    ("х", "x"),
    ("ц", "ts"),
    ("ч", "ch"),
    ("ш", "sh"),
    ("щ", "sch"),
    ("ъ", ""),
    ("ы", "y"),
    ("ь", ""),
    ("э", "e"),
    ("ю", "yu"),
    ("я", "ya"),
    ("А", "A"),
    ("Б", "B"),
    ("В", "V"),
    ("Г", "G"),
    ("Д", "D"),
    ("Е", "E"),
    ("Ё", "E"),
    ("Ж", "ZH"),
    ("З", "Z"),
    ("И", "I"),
    ("Й", "I"),
    ("К", "K"),
    ("Л", "L"),
    ("М", "M"),
    ("Н", "N"),
    ("О", "O"),
    ("П", "P"),
    ("Р", "R"),
    ("С", "S"),
    ("Т", "T"),
    ("У", "U"),
    ("Ф", "F"),
    ("Х", "X"),
    ("Ц", "TS"),
    ("Ч", "CH"),
    ("Ш", "SH"),
    ("Щ", "SCH"),
    ("Ъ", ""),
    ("Ы", "Y"),
    ("Ь", ""),
    ("Э", "E"),
    ("Ю", "YU"),
    ("Я", "YA"),
)

ARMENIAN_REPLACEMENTS = (
    ("ա", "a"),
    ("բ", "b"),
    ("գ", "g"),
    ("դ", "d"),
    ("ե", "e"),
    ("զ", "z"),
    ("է", "e"),
    ("ը", "y"),
    ("թ", "t"),
    ("ժ", "zh"),
    ("ի", "i"),
    ("լ", "l"),
    ("խ", "kh"),
    ("ծ", "ts"),
    ("կ", "k"),
    ("հ", "h"),
    ("ձ", "dz"),
    ("ղ", "gh"),
    ("ճ", "ch"),
    ("մ", "m"),
    ("յ", "y"),
    ("ն", "n"),
    ("շ", "sh"),
    ("ո", "o"),
    ("չ", "ch"),
    ("պ", "p"),
    ("ջ", "j"),
    ("ռ", "r"),
    ("ս", "s"),
    ("վ", "v"),
    ("տ", "t"),
    ("ր", "r"),
    ("ց", "ts"),
    ("ու", "u"),
    ("փ", "p"),
    ("ք", "k"),
    ("օ", "o"),
    ("ֆ", "f"),
    ("և", "ev"),
)

HEBREW_REPLACEMENTS = (
    ("א", "a"),
    ("ב", "b"),
    ("ג", "g"),
    ("ד", "d"),
    ("ה", "h"),
    ("ו", "v"),
    ("ז", "z"),
    ("ח", "kh"),
    ("ט", "t"),
    ("י", "y"),
    ("כ", "k"),
    ("ך", "k"),
    ("ל", "l"),
    ("מ", "m"),
    ("ם", "m"),
    ("נ", "n"),
    ("ן", "n"),
    ("ס", "s"),
    ("ע", "a"),
    ("פ", "p"),
    ("ף", "p"),
    ("צ", "ts"),
    ("ץ", "ts"),
    ("ק", "q"),
    ("ר", "r"),
    ("ש", "sh"),
    ("ת", "t"),
)

ARABIC_REPLACEMENTS = (
    ("ا", "a"),
    ("أ", "a"),
    ("إ", "i"),
    ("آ", "aa"),
    ("ب", "b"),
    ("ت", "t"),
    ("ث", "th"),
    ("ج", "j"),
    ("ح", "h"),
    ("خ", "kh"),
    ("د", "d"),
    ("ذ", "dh"),
    ("ر", "r"),
    ("ز", "z"),
    ("س", "s"),
    ("ش", "sh"),
    ("ص", "s"),
    ("ض", "d"),
    ("ط", "t"),
    ("ظ", "z"),
    ("ع", "a"),
    ("غ", "gh"),
    ("ف", "f"),
    ("ق", "q"),
    ("ك", "k"),
    ("ل", "l"),
    ("م", "m"),
    ("ن", "n"),
    ("ه", "h"),
    ("و", "w"),
    ("ي", "y"),
    ("ة", "h"),
    ("ى", "a"),
    ("٠", "0"),
    ("١", "1"),
    ("٢", "2"),
    ("٣", "3"),
    ("٤", "4"),
    ("٥", "5"),
    ("٦", "6"),
    ("٧", "7"),
    ("٨", "8"),
    ("٩", "9"),
)

GEORGIAN_REPLACEMENTS = (
    ("ა", "a"),
    ("ბ", "b"),
    ("გ", "g"),
    ("დ", "d"),
    ("ე", "e"),
    ("ვ", "v"),
    ("ზ", "z"),
    ("თ", "t"),
    ("ი", "i"),
    ("კ", "k"),
    ("ლ", "l"),
    ("მ", "m"),
    ("ნ", "n"),
    ("ო", "o"),
    ("პ", "p"),
    ("ჟ", "zh"),
    ("რ", "r"),
    ("ს", "s"),
    ("ტ", "t"),
    ("უ", "u"),
    ("ფ", "p"),
    ("ქ", "k"),
    ("ღ", "gh"),
    ("ყ", "q"),
    ("შ", "sh"),
    ("ჩ", "ch"),
    ("ც", "ts"),
    ("ძ", "dz"),
    ("წ", "ts"),
    ("ჭ", "ch"),
    ("ხ", "kh"),
    ("ჯ", "j"),
    ("ჰ", "h"),
)

DEVANAGARI_REPLACEMENTS = (
    ("अ", "a"),
    ("आ", "aa"),
    ("इ", "i"),
    ("ई", "ii"),
    ("उ", "u"),
    ("ऊ", "uu"),
    ("ए", "e"),
    ("ऐ", "ai"),
    ("ओ", "o"),
    ("औ", "au"),
    ("क", "k"),
    ("ख", "kh"),
    ("ग", "g"),
    ("घ", "gh"),
    ("च", "ch"),
    ("छ", "chh"),
    ("ज", "j"),
    ("झ", "jh"),
    ("ट", "t"),
    ("ठ", "th"),
    ("ड", "d"),
    ("ढ", "dh"),
    ("ण", "n"),
    ("त", "t"),
    ("थ", "th"),
    ("द", "d"),
    ("ध", "dh"),
    ("न", "n"),
    ("प", "p"),
    ("फ", "ph"),
    ("ब", "b"),
    ("भ", "bh"),
    ("म", "m"),
    ("य", "y"),
    ("र", "r"),
    ("ल", "l"),
    ("व", "v"),
    ("श", "sh"),
    ("ष", "sh"),
    ("स", "s"),
    ("ह", "h"),
    ("ं", "n"),
    ("ः", "h"),
    ("ँ", "n"),
    ("्", ""),
)

BENGALI_REPLACEMENTS = (
    ("অ", "a"),
    ("আ", "aa"),
    ("ই", "i"),
    ("ঈ", "ii"),
    ("উ", "u"),
    ("ঊ", "uu"),
    ("এ", "e"),
    ("ঐ", "oi"),
    ("ও", "o"),
    ("ঔ", "ou"),
    ("ক", "k"),
    ("খ", "kh"),
    ("গ", "g"),
    ("ঘ", "gh"),
    ("চ", "ch"),
    ("ছ", "chh"),
    ("জ", "j"),
    ("ঝ", "jh"),
    ("ট", "t"),
    ("ঠ", "th"),
    ("ড", "d"),
    ("ঢ", "dh"),
    ("ণ", "n"),
    ("ত", "t"),
    ("থ", "th"),
    ("দ", "d"),
    ("ধ", "dh"),
    ("ন", "n"),
    ("প", "p"),
    ("ফ", "ph"),
    ("ব", "b"),
    ("ভ", "bh"),
    ("ম", "m"),
    ("য", "y"),
    ("র", "r"),
    ("ল", "l"),
    ("শ", "sh"),
    ("ষ", "sh"),
    ("স", "s"),
    ("হ", "h"),
    ("া", "a"),
    ("ি", "i"),
    ("ী", "ii"),
    ("ু", "u"),
    ("ূ", "uu"),
    ("ে", "e"),
    ("ৈ", "oi"),
    ("ো", "o"),
    ("ৌ", "ou"),
    ("ং", "ng"),
    ("ঃ", "h"),
    ("ঁ", "n"),
    ("্", ""),
    ("০", "0"),
    ("১", "1"),
    ("২", "2"),
    ("৩", "3"),
    ("৪", "4"),
    ("৫", "5"),
    ("৬", "6"),
    ("৭", "7"),
    ("৮", "8"),
    ("৯", "9"),
)

HIRAGANA_REPLACEMENTS = (
    ("あ", "a"),
    ("い", "i"),
    ("う", "u"),
    ("え", "e"),
    ("お", "o"),
    ("か", "ka"),
    ("き", "ki"),
    ("く", "ku"),
    ("け", "ke"),
    ("こ", "ko"),
    ("さ", "sa"),
    ("し", "shi"),
    ("す", "su"),
    ("せ", "se"),
    ("そ", "so"),
    ("た", "ta"),
    ("ち", "chi"),
    ("つ", "tsu"),
    ("て", "te"),
    ("と", "to"),
    ("な", "na"),
    ("に", "ni"),
    ("ぬ", "nu"),
    ("ね", "ne"),
    ("の", "no"),
    ("は", "ha"),
    ("ひ", "hi"),
    ("ふ", "fu"),
    ("へ", "he"),
    ("ほ", "ho"),
    ("ま", "ma"),
    ("み", "mi"),
    ("む", "mu"),
    ("め", "me"),
    ("も", "mo"),
    ("や", "ya"),
    ("ゆ", "yu"),
    ("よ", "yo"),
    ("ら", "ra"),
    ("り", "ri"),
    ("る", "ru"),
    ("れ", "re"),
    ("ろ", "ro"),
    ("わ", "wa"),
    ("を", "wo"),
    ("ん", "n"),
)

KATAKANA_REPLACEMENTS = (
    ("ア", "a"),
    ("イ", "i"),
    ("ウ", "u"),
    ("エ", "e"),
    ("オ", "o"),
    ("カ", "ka"),
    ("キ", "ki"),
    ("ク", "ku"),
    ("ケ", "ke"),
    ("コ", "ko"),
    ("サ", "sa"),
    ("シ", "shi"),
    ("ス", "su"),
    ("セ", "se"),
    ("ソ", "so"),
    ("タ", "ta"),
    ("チ", "chi"),
    ("ツ", "tsu"),
    ("テ", "te"),
    ("ト", "to"),
    ("ナ", "na"),
    ("ニ", "ni"),
    ("ヌ", "nu"),
    ("ネ", "ne"),
    ("ノ", "no"),
    ("ハ", "ha"),
    ("ヒ", "hi"),
    ("フ", "fu"),
    ("ヘ", "he"),
    ("ホ", "ho"),
    ("マ", "ma"),
    ("ミ", "mi"),
    ("ム", "mu"),
    ("メ", "me"),
    ("モ", "mo"),
    ("ヤ", "ya"),
    ("ユ", "yu"),
    ("ヨ", "yo"),
    ("ラ", "ra"),
    ("リ", "ri"),
    ("ル", "ru"),
    ("レ", "re"),
    ("ロ", "ro"),
    ("ワ", "wa"),
    ("ヲ", "wo"),
    ("ン", "n"),
)

FULLWIDTH_REPLACEMENTS = (
    ("！", "!"),
    ("＂", '"'),
    ("＃", "#"),
    ("＄", "$"),
    ("％", "%"),
    ("＆", "&"),
    ("＇", "'"),
    ("（", "("),
    ("）", ")"),
    ("＊", "*"),
    ("＋", "+"),
    ("，", ","),
    ("－", "-"),
    ("．", "."),
    ("／", "/"),
    ("０", "0"),
    ("１", "1"),
    ("２", "2"),
    ("３", "3"),
    ("４", "4"),
    ("５", "5"),
    ("６", "6"),
    ("７", "7"),
    ("８", "8"),
    ("９", "9"),
    ("：", ":"),
    ("；", ";"),
    ("＜", "<"),
    ("＝", "="),
    ("＞", ">"),
    ("？", "?"),
    ("＠", "@"),
    ("Ａ", "A"),
    ("Ｂ", "B"),
    ("Ｃ", "C"),
    ("Ｄ", "D"),
    ("Ｅ", "E"),
    ("Ｆ", "F"),
    ("Ｇ", "G"),
    ("Ｈ", "H"),
    ("Ｉ", "I"),
    ("Ｊ", "J"),
    ("Ｋ", "K"),
    ("Ｌ", "L"),
    ("Ｍ", "M"),
    ("Ｎ", "N"),
    ("Ｏ", "O"),
    ("Ｐ", "P"),
    ("Ｑ", "Q"),
    ("Ｒ", "R"),
    ("Ｓ", "S"),
    ("Ｔ", "T"),
    ("Ｕ", "U"),
    ("Ｖ", "V"),
    ("Ｗ", "W"),
    ("Ｘ", "X"),
    ("Ｙ", "Y"),
    ("Ｚ", "Z"),
    ("ａ", "a"),
    ("ｂ", "b"),
    ("ｃ", "c"),
    ("ｄ", "d"),
    ("ｅ", "e"),
    ("ｆ", "f"),
    ("ｇ", "g"),
    ("ｈ", "h"),
    ("ｉ", "i"),
    ("ｊ", "j"),
    ("ｋ", "k"),
    ("ｌ", "l"),
    ("ｍ", "m"),
    ("ｎ", "n"),
    ("ｏ", "o"),
    ("ｐ", "p"),
    ("ｑ", "q"),
    ("ｒ", "r"),
    ("ｓ", "s"),
    ("ｔ", "t"),
    ("ｕ", "u"),
    ("ｖ", "v"),
    ("ｗ", "w"),
    ("ｘ", "x"),
    ("ｙ", "y"),
    ("ｚ", "z"),
    ("［", "["),
    ("］", "]"),
    ("｛", "{"),
    ("｝", "}"),
    ("＼", "\\"),
    ("｜", "|"),
    ("〜", "~"),
)


THAI_REPLACEMENTS = (
    ("ก", "k"),
    ("ข", "kh"),
    ("ค", "kh"),
    ("ง", "ng"),
    ("จ", "ch"),
    ("ฉ", "ch"),
    ("ช", "ch"),
    ("ซ", "s"),
    ("ด", "d"),
    ("ต", "t"),
    ("ถ", "th"),
    ("ท", "th"),
    ("น", "n"),
    ("บ", "b"),
    ("ป", "p"),
    ("ผ", "ph"),
    ("พ", "ph"),
    ("ม", "m"),
    ("ย", "y"),
    ("ร", "r"),
    ("ล", "l"),
    ("ว", "w"),
    ("ศ", "s"),
    ("ษ", "s"),
    ("ส", "s"),
    ("ห", "h"),
    ("อ", "o"),
    ("า", "a"),
    ("ิ", "i"),
    ("ี", "ii"),
    ("ึ", "ue"),
    ("ื", "ue"),
    ("ุ", "u"),
    ("ู", "u"),
    ("เ", "e"),
    ("แ", "ae"),
    ("โ", "o"),
    ("ใ", "ai"),
    ("ไ", "ai"),
    ("ำ", "am"),
    ("่", ""),
    ("้", ""),
    ("๊", ""),
    ("๋", ""),
    ("ๆ", ""),
    ("๐", "0"),
    ("๑", "1"),
    ("๒", "2"),
    ("๓", "3"),
    ("๔", "4"),
    ("๕", "5"),
    ("๖", "6"),
    ("๗", "7"),
    ("๘", "8"),
    ("๙", "9"),
)

LAO_REPLACEMENTS = (
    ("ກ", "k"),
    ("ຂ", "kh"),
    ("ຄ", "kh"),
    ("ງ", "ng"),
    ("ຈ", "ch"),
    ("ສ", "s"),
    ("ຊ", "s"),
    ("ຍ", "ny"),
    ("ດ", "d"),
    ("ຕ", "t"),
    ("ຖ", "th"),
    ("ທ", "th"),
    ("ນ", "n"),
    ("ບ", "b"),
    ("ປ", "p"),
    ("ຜ", "ph"),
    ("ຝ", "f"),
    ("ພ", "ph"),
    ("ຟ", "f"),
    ("ມ", "m"),
    ("ຢ", "y"),
    ("ຣ", "r"),
    ("ລ", "l"),
    ("ວ", "w"),
    ("ຫ", "h"),
    ("ອ", "o"),
    ("ະ", "a"),
    ("ັ", "a"),
    ("າ", "aa"),
    ("ິ", "i"),
    ("ີ", "ii"),
    ("ຶ", "ue"),
    ("ື", "ue"),
    ("ຸ", "u"),
    ("ູ", "uu"),
    ("ເ", "e"),
    ("ແ", "ae"),
    ("ໂ", "o"),
    ("ໃ", "ai"),
    ("ໄ", "ai"),
    ("່", ""),
    ("້", ""),
    ("໊", ""),
    ("໋", ""),
    ("ໍ", "o"),
    ("ໜ", "n"),
    ("ໝ", "m"),
    ("໐", "0"),
    ("໑", "1"),
    ("໒", "2"),
    ("໓", "3"),
    ("໔", "4"),
    ("໕", "5"),
    ("໖", "6"),
    ("໗", "7"),
    ("໘", "8"),
    ("໙", "9"),
)

SINHALA_REPLACEMENTS = (
    ("අ", "a"),
    ("ආ", "aa"),
    ("ඇ", "ae"),
    ("ඉ", "i"),
    ("ඊ", "ii"),
    ("උ", "u"),
    ("ඌ", "uu"),
    ("එ", "e"),
    ("ඔ", "o"),
    ("ක", "k"),
    ("ග", "g"),
    ("ච", "ch"),
    ("ජ", "j"),
    ("ට", "t"),
    ("ඩ", "d"),
    ("ත", "t"),
    ("ද", "d"),
    ("න", "n"),
    ("ප", "p"),
    ("බ", "b"),
    ("ම", "m"),
    ("ය", "y"),
    ("ර", "r"),
    ("ල", "l"),
    ("ව", "v"),
    ("ස", "s"),
    ("හ", "h"),
    ("ා", "a"),
    ("ැ", "ae"),
    ("ි", "i"),
    ("ී", "ii"),
    ("ු", "u"),
    ("ූ", "uu"),
    ("ෙ", "e"),
    ("ො", "o"),
    ("්", ""),
    ("෴", ""),
    ("෦", "0"),
    ("෧", "1"),
    ("෨", "2"),
    ("෩", "3"),
    ("෪", "4"),
    ("෫", "5"),
    ("෬", "6"),
    ("෭", "7"),
    ("෮", "8"),
    ("෯", "9"),
)

TAMIL_REPLACEMENTS = (
    ("அ", "a"),
    ("ஆ", "aa"),
    ("இ", "i"),
    ("ஈ", "ii"),
    ("உ", "u"),
    ("ஊ", "uu"),
    ("எ", "e"),
    ("ஏ", "ee"),
    ("ஒ", "o"),
    ("ஓ", "oo"),
    ("க", "k"),
    ("ங", "ng"),
    ("ச", "ch"),
    ("ஞ", "ny"),
    ("ட", "t"),
    ("ண", "n"),
    ("த", "t"),
    ("ந", "n"),
    ("ப", "p"),
    ("ம", "m"),
    ("ய", "y"),
    ("ர", "r"),
    ("ல", "l"),
    ("வ", "v"),
    ("ழ", "zh"),
    ("ள", "l"),
    ("ற", "r"),
    ("ன", "n"),
    ("ா", "a"),
    ("ி", "i"),
    ("ீ", "ii"),
    ("ு", "u"),
    ("ூ", "uu"),
    ("ெ", "e"),
    ("ே", "ee"),
    ("ொ", "o"),
    ("ோ", "oo"),
    ("்", ""),
    ("௦", "0"),
    ("௧", "1"),
    ("௨", "2"),
    ("௩", "3"),
    ("௪", "4"),
    ("௫", "5"),
    ("௬", "6"),
    ("௭", "7"),
    ("௮", "8"),
    ("௯", "9"),
)

TELUGU_REPLACEMENTS = (
    ("అ", "a"),
    ("ఆ", "aa"),
    ("ఇ", "i"),
    ("ఈ", "ii"),
    ("ఉ", "u"),
    ("ఊ", "uu"),
    ("ఎ", "e"),
    ("ఏ", "ee"),
    ("ఒ", "o"),
    ("ఓ", "oo"),
    ("క", "k"),
    ("ఖ", "kh"),
    ("గ", "g"),
    ("ఘ", "gh"),
    ("చ", "ch"),
    ("జ", "j"),
    ("ట", "t"),
    ("డ", "d"),
    ("త", "t"),
    ("ద", "d"),
    ("న", "n"),
    ("ప", "p"),
    ("ఫ", "ph"),
    ("బ", "b"),
    ("మ", "m"),
    ("య", "y"),
    ("ర", "r"),
    ("ల", "l"),
    ("వ", "v"),
    ("శ", "sh"),
    ("ష", "sh"),
    ("స", "s"),
    ("హ", "h"),
    ("ా", "a"),
    ("ి", "i"),
    ("ీ", "ii"),
    ("ు", "u"),
    ("ూ", "uu"),
    ("ె", "e"),
    ("ే", "ee"),
    ("ొ", "o"),
    ("ో", "oo"),
    ("్", ""),
    ("౦", "0"),
    ("౧", "1"),
    ("౨", "2"),
    ("౩", "3"),
    ("౪", "4"),
    ("౫", "5"),
    ("౬", "6"),
    ("౭", "7"),
    ("౮", "8"),
    ("౯", "9"),
)

KANNADA_REPLACEMENTS = (
    ("ಅ", "a"),
    ("ಆ", "aa"),
    ("ಇ", "i"),
    ("ಈ", "ii"),
    ("ಉ", "u"),
    ("ಊ", "uu"),
    ("ಎ", "e"),
    ("ಏ", "ee"),
    ("ಒ", "o"),
    ("ಓ", "oo"),
    ("ಕ", "k"),
    ("ಖ", "kh"),
    ("ಗ", "g"),
    ("ಘ", "gh"),
    ("ಚ", "ch"),
    ("ಜ", "j"),
    ("ಟ", "t"),
    ("ಡ", "d"),
    ("ತ", "t"),
    ("ದ", "d"),
    ("ನ", "n"),
    ("ಪ", "p"),
    ("ಫ", "ph"),
    ("ಬ", "b"),
    ("ಮ", "m"),
    ("ಯ", "y"),
    ("ರ", "r"),
    ("ಲ", "l"),
    ("ವ", "v"),
    ("ಶ", "sh"),
    ("ಷ", "sh"),
    ("ಸ", "s"),
    ("ಹ", "h"),
    ("ಾ", "a"),
    ("ಿ", "i"),
    ("ೀ", "ii"),
    ("ು", "u"),
    ("ೂ", "uu"),
    ("ೆ", "e"),
    ("ೇ", "ee"),
    ("ೊ", "o"),
    ("ೋ", "oo"),
    ("್", ""),
    ("೦", "0"),
    ("೧", "1"),
    ("೨", "2"),
    ("೩", "3"),
    ("೪", "4"),
    ("೫", "5"),
    ("೬", "6"),
    ("೭", "7"),
    ("೮", "8"),
    ("೯", "9"),
)

MALAYALAM_REPLACEMENTS = (
    ("അ", "a"),
    ("ആ", "aa"),
    ("ഇ", "i"),
    ("ഈ", "ii"),
    ("ഉ", "u"),
    ("ഊ", "uu"),
    ("എ", "e"),
    ("ഏ", "ee"),
    ("ഒ", "o"),
    ("ഓ", "oo"),
    ("ക", "k"),
    ("ഖ", "kh"),
    ("ഗ", "g"),
    ("ഘ", "gh"),
    ("ച", "ch"),
    ("ജ", "j"),
    ("ട", "t"),
    ("ഡ", "d"),
    ("ത", "t"),
    ("ദ", "d"),
    ("ന", "n"),
    ("പ", "p"),
    ("ഫ", "ph"),
    ("ബ", "b"),
    ("മ", "m"),
    ("യ", "y"),
    ("ര", "r"),
    ("ല", "l"),
    ("വ", "v"),
    ("ശ", "sh"),
    ("ഷ", "sh"),
    ("സ", "s"),
    ("ഹ", "h"),
    ("ാ", "a"),
    ("ി", "i"),
    ("ീ", "ii"),
    ("ു", "u"),
    ("ൂ", "uu"),
    ("െ", "e"),
    ("േ", "ee"),
    ("ൊ", "o"),
    ("ോ", "oo"),
    ("്", ""),
    ("൦", "0"),
    ("൧", "1"),
    ("൨", "2"),
    ("൩", "3"),
    ("൪", "4"),
    ("൫", "5"),
    ("൬", "6"),
    ("൭", "7"),
    ("൮", "8"),
    ("൯", "9"),
)

MYANMAR_REPLACEMENTS = (
    ("က", "k"),
    ("ခ", "kh"),
    ("ဂ", "g"),
    ("ဃ", "gh"),
    ("င", "ng"),
    ("စ", "s"),
    ("ဆ", "s"),
    ("ဇ", "z"),
    ("ည", "ny"),
    ("တ", "t"),
    ("ထ", "th"),
    ("ဒ", "d"),
    ("န", "n"),
    ("ပ", "p"),
    ("ဖ", "ph"),
    ("ဗ", "b"),
    ("မ", "m"),
    ("ယ", "y"),
    ("ရ", "r"),
    ("လ", "l"),
    ("ဝ", "w"),
    ("သ", "th"),
    ("ဟ", "h"),
    ("ဣ", "i"),
    ("ဤ", "ii"),
    ("ဥ", "u"),
    ("ဦ", "uu"),
    ("ဧ", "e"),
    ("ဩ", "o"),
    ("ာ", "a"),
    ("ိ", "i"),
    ("ီ", "ii"),
    ("ု", "u"),
    ("ူ", "uu"),
    ("ေ", "e"),
    ("ဲ", "ai"),
    ("ံ", "n"),
    ("့", ""),
    ("း", ""),
    ("၀", "0"),
    ("၁", "1"),
    ("၂", "2"),
    ("၃", "3"),
    ("၄", "4"),
    ("၅", "5"),
    ("၆", "6"),
    ("၇", "7"),
    ("၈", "8"),
    ("၉", "9"),
)

KOREAN_REPLACEMENTS = (
    ("㈜", "(주)"),
    ("㈱", "(주)"),
    ("㉿", "대한민국"),
    ("㏂", "오전"),
    ("㏘", "오후"),
    ("㍿", "주식회사"),
    ("©", "저작권"),
    ("®", "등록상표"),
    ("™", "상표"),
    ("№", "번호"),
    ("℃", "도씨"),
    ("℉", "화씨"),
    ("a.m.", "오전"),
    ("p.m.", "오후"),
    ("TM", "상표"),
    ("No", "번호"),
    ("㎏", "kg"),
    ("㎍", "ug"),
    ("㎎", "mg"),
    ("㎖", "ml"),
    ("㎘", "kl"),
    ("㎝", "cm"),
    ("㎞", "km"),
    ("㏄", "cc"),
    ("㎐", "hz"),
    ("㎔", "thz"),
    ("㎩", "pa"),
    ("㎬", "gb"),
    ("㏊", "ha"),
)

SYMBOL_REPLACEMENTS = (
    ("©", "(c)"),
    ("®", "(r)"),
    ("™", "tm"),
    ("℠", "sm"),
    ("№", "no"),
    ("§", "s"),
    ("¶", "p"),
    ("‰", "/1000"),
    ("×", "x"),
    ("÷", "/"),
    ("±", "+/-"),
    ("√", "sqrt"),
    ("∞", "inf"),
    ("µ", "u"),
    ("°", "deg"),
    ("¼", "1/4"),
    ("½", "1/2"),
    ("¾", "3/4"),
    ("¹", "1"),
    ("²", "2"),
    ("³", "3"),
    ("⁴", "4"),
    ("⁵", "5"),
    ("⁶", "6"),
    ("⁷", "7"),
    ("⁸", "8"),
    ("⁹", "9"),
    ("⁰", "0"),
    ("₀", "0"),
    ("₁", "1"),
    ("₂", "2"),
    ("₃", "3"),
    ("₄", "4"),
    ("₅", "5"),
    ("₆", "6"),
    ("₇", "7"),
    ("₈", "8"),
    ("₉", "9"),
    ("∩", "n"),
    ("∪", "u"),
    ("∑", "sum"),
    ("∏", "prod"),
    ("∂", "d"),
    ("∆", "delta"),
    ("≠", "!="),
    ("≈", "~"),
    ("≤", "<="),
    ("≥", ">="),
    ("←", "<-"),
    ("→", "->"),
    ("↑", "^"),
    ("↓", "v"),
    ("↔", "<->"),
    ("↕", "<->"),
    ("↖", "nw"),
    ("↗", "ne"),
    ("↘", "se"),
    ("↙", "sw"),
    ("↩", "<-"),
    ("↪", "->"),
    ("⇐", "<="),
    ("⇒", "=>"),
    ("⇔", "<=>"),
    ("←", "<-"),
    ("→", "->"),
    ("↑", "^"),
    ("↓", "v"),
    ("↦", "->"),
    ("↤", "<-"),
    ("∼", "~"),
    ("∽", "~"),
    ("∝", "prop"),
    ("∞", "inf"),
    ("∅", "empty"),
    ("∈", "in"),
    ("∉", "not in"),
    ("∋", "contains"),
    ("∌", "not contains"),
    ("∧", "and"),
    ("∨", "or"),
    ("⊕", "+"),
    ("⊗", "x"),
    ("⊙", "o"),
    ("≃", "~"),
    ("≅", "~"),
    ("≡", "="),
    ("≤", "<="),
    ("≥", ">="),
    ("≪", "<<"),
    ("≫", ">>"),
    ("≺", "<"),
    ("≻", ">"),
    ("≼", "<="),
    ("≽", ">="),
    ("⊂", "subset"),
    ("⊃", "superset"),
    ("⊆", "subseteq"),
    ("⊇", "superseteq"),
    ("✓", "v"),
    ("✔", "v"),
    ("✕", "x"),
    ("✖", "x"),
    ("✚", "+"),
    ("★", "*"),
    ("☆", "*"),
    ("✦", "*"),
    ("✧", "*"),
    ("✩", "*"),
    ("✪", "*"),
    ("♥", "heart"),
    ("♡", "heart"),
    ("♠", "spade"),
    ("♣", "club"),
    ("♦", "diamond"),
    ("♪", "note"),
    ("♫", "music"),
    ("☀", "sun"),
    ("☁", "cloud"),
    ("☂", "umbrella"),
    ("☃", "snowman"),
    ("☕", "coffee"),
    ("☘", "clover"),
    ("☑", "[x]"),
    ("☐", "[ ]"),
    ("①", "1"),
    ("②", "2"),
    ("③", "3"),
    ("④", "4"),
    ("⑤", "5"),
    ("⑥", "6"),
    ("⑦", "7"),
    ("⑧", "8"),
    ("⑨", "9"),
    ("⑩", "10"),
    ("⑪", "11"),
    ("⑫", "12"),
    ("⑬", "13"),
    ("⑭", "14"),
    ("⑮", "15"),
    ("⑯", "16"),
    ("⑰", "17"),
    ("⑱", "18"),
    ("⑲", "19"),
    ("⑳", "20"),
)

ASCII_DIGIT_MAP = tuple((chr(code), str(code - 48)) for code in range(ord("0"), ord("9") + 1))

COMBINING_MARK_CATEGORIES = {"Mn", "Mc", "Me"}

KOREAN_CONFUSABLE_REPLACEMENTS = (
    ("⋌∣", "시"),
    ("\u0aee\u0aa4\u0acd\u0ab0\u0ac1", "녕"),
    ("\u0c17\u0ac1", "입"),
    ("\u0aa6\u0306\u030e", "다"),
    ("ᴋ", "k"),
    ("ᴍ", "m"),
    ("ᴘ", "p"),
    ("ᴛ", "t"),
    ("ʜ", "h"),
    ("ʏ", "y"),
    ("ɴ", "n"),
    ("ɡ", "g"),
    ("ᄀ", "g"),
    ("ᄂ", "n"),
    ("ᄃ", "d"),
    ("ᄅ", "r"),
    ("ᄆ", "m"),
    ("ᄇ", "b"),
    ("ᄉ", "s"),
    ("ᄋ", "ng"),
    ("ᄌ", "j"),
    ("ᄎ", "ch"),
    ("ᄏ", "k"),
    ("ᄐ", "t"),
    ("ᄑ", "p"),
    ("ᄒ", "h"),
    ("ᴥ", ""),
    ("ː", ""),
    ("ˑ", ""),
    ("ˉ", ""),
    ("ˇ", ""),
    ("˘", ""),
    ("˝", ""),
    ("˚", ""),
    ("·", ""),
    ("⋅", ""),
    ("∣", "ㅣ"),
    ("⫣", "ㅔ"),
    ("⋌", "ㅅ"),
    ("⋸", "트"),
    ("⩟", "스"),
    ("ગ", "이"),
    ("ග", "이"),
    ("\u0c17", "이"),
    ("ન", "어"),
    ("પ", "니"),
    ("દ", "다"),
)

KEEP_PUNCTUATION = set(".?!,;:'\"-()[]{}<>/\\@#&%+*=|_^~`…·•《》〈〉「」『』、。！？；：")

REPLACEMENT_ORDER = {
    "en": (
        GENERAL_REPLACEMENTS,
        FULLWIDTH_REPLACEMENTS,
        LATIN_REPLACEMENTS,
        GREEK_REPLACEMENTS,
        CYRILLIC_REPLACEMENTS,
        HIRAGANA_REPLACEMENTS,
        KATAKANA_REPLACEMENTS,
        ARMENIAN_REPLACEMENTS,
        HEBREW_REPLACEMENTS,
        ARABIC_REPLACEMENTS,
        GEORGIAN_REPLACEMENTS,
        DEVANAGARI_REPLACEMENTS,
        BENGALI_REPLACEMENTS,
        THAI_REPLACEMENTS,
        LAO_REPLACEMENTS,
        SINHALA_REPLACEMENTS,
        TAMIL_REPLACEMENTS,
        TELUGU_REPLACEMENTS,
        KANNADA_REPLACEMENTS,
        MALAYALAM_REPLACEMENTS,
        MYANMAR_REPLACEMENTS,
        SYMBOL_REPLACEMENTS,
    ),
    "ko": (
        GENERAL_REPLACEMENTS,
        KOREAN_REPLACEMENTS,
        KOREAN_CONFUSABLE_REPLACEMENTS,
        FULLWIDTH_REPLACEMENTS,
        LATIN_REPLACEMENTS,
        GREEK_REPLACEMENTS,
        CYRILLIC_REPLACEMENTS,
        HIRAGANA_REPLACEMENTS,
        KATAKANA_REPLACEMENTS,
        ARMENIAN_REPLACEMENTS,
        HEBREW_REPLACEMENTS,
        ARABIC_REPLACEMENTS,
        GEORGIAN_REPLACEMENTS,
        DEVANAGARI_REPLACEMENTS,
        BENGALI_REPLACEMENTS,
        THAI_REPLACEMENTS,
        LAO_REPLACEMENTS,
        SINHALA_REPLACEMENTS,
        TAMIL_REPLACEMENTS,
        TELUGU_REPLACEMENTS,
        KANNADA_REPLACEMENTS,
        MALAYALAM_REPLACEMENTS,
        MYANMAR_REPLACEMENTS,
        SYMBOL_REPLACEMENTS,
    ),
}

KOREAN_PRE_REPLACEMENTS = (
    ("\u0aee\u0aa4\u0acd\u0ab0\u0ac1", "녕"),
    ("\u0c17\u0ac1", "입"),
    ("\u0aa6\u0306\u030e", "다"),
    ("⋌⫣", "세"),
    ("⋌∣", "시"),
)


def _flatten_replacements(groups: Iterable[Iterable[tuple[str, str]]]) -> list[tuple[str, str]]:
    flattened: list[tuple[str, str]] = []
    for group in groups:
        flattened.extend(group)
    flattened.extend(ASCII_DIGIT_MAP)
    flattened.sort(key=lambda item: len(item[0]), reverse=True)
    return flattened


def _apply_replacements(text: str, replacements: Iterable[tuple[str, str]]) -> str:
    for source, target in replacements:
        text = text.replace(source, target)
    return text


def _strip_combining_marks(text: str) -> str:
    decomposed = unicodedata.normalize("NFKD", text)
    return "".join(char for char in decomposed if unicodedata.category(char) not in COMBINING_MARK_CATEGORIES)


def _keep_character_in_korean_cleanup(char: str) -> bool:
    if char.isspace():
        return True
    if char.isdigit() or char.isascii() and char.isalpha():
        return True
    if char in KEEP_PUNCTUATION:
        return True

    codepoint = ord(char)
    return (
        0xAC00 <= codepoint <= 0xD7A3
        or 0x1100 <= codepoint <= 0x11FF
        or 0x3130 <= codepoint <= 0x318F
        or 0xA960 <= codepoint <= 0xA97F
        or 0xD7B0 <= codepoint <= 0xD7FF
    )


def _cleanup_non_korean_letters(text: str) -> str:
    return "".join(char for char in text if _keep_character_in_korean_cleanup(char))


def _normalize_unicode_digits(text: str, drop_non_ascii_digits: bool = False) -> str:
    normalized_characters = []
    for char in text:
        if char.isdigit():
            if drop_non_ascii_digits and not char.isascii():
                continue
            try:
                normalized_characters.append(str(unicodedata.digit(char)))
                continue
            except (TypeError, ValueError):
                pass
        normalized_characters.append(char)
    return "".join(normalized_characters)


def _compose_hangul(text: str) -> str:
    return unicodedata.normalize("NFC", text)


_WORD_TO_DIGIT = {
    "ZERO": "0",
    "ONE": "1",
    "TWO": "2",
    "THREE": "3",
    "FOUR": "4",
    "FIVE": "5",
    "SIX": "6",
    "SEVEN": "7",
    "EIGHT": "8",
    "NINE": "9",
}


def _map_mathematical_alphanumerics(text: str) -> str:
    """Map characters from the Mathematical Alphanumeric Symbols block
    (and similar named characters) back to plain ASCII letters/digits.
    This handles characters whose Unicode name contains 'MATHEMATICAL'.
    """
    out_chars: list[str] = []
    for ch in text:
        try:
            name = unicodedata.name(ch)
        except ValueError:
            out_chars.append(ch)
            continue

        if "MATHEMATICAL" in name:
            tokens = name.split()
            # handle digits like 'MATHEMATICAL BOLD DIGIT THREE'
            if "DIGIT" in tokens:
                word = tokens[-1]
                mapped = _WORD_TO_DIGIT.get(word, None)
                if mapped is not None:
                    out_chars.append(mapped)
                    continue
            # handle letters — check for CAPITAL/SMALL to preserve case
            letter = tokens[-1]
            if len(letter) == 1 and letter.isalpha():
                if "SMALL" in tokens:
                    out_chars.append(letter.lower())
                else:
                    out_chars.append(letter.upper())
                continue

        out_chars.append(ch)
    return "".join(out_chars)


def special_text(text: str, preferred_language: str = "en", cleanup_non_korean: bool = False) -> str:
    """
    Convert stylized and multilingual special characters to plain text.

    preferred_language accepts:
    - "en": prioritize Latin-style normalization
    - "ko": prioritize Korean-specific replacements first

    cleanup_non_korean removes unsupported foreign-script letters after
    normalization, which is useful for heavily decorated Korean text.
    """
    normalized_language = preferred_language.lower().strip()
    if normalized_language not in REPLACEMENT_ORDER:
        normalized_language = "en"

    if normalized_language == "ko":
        text = _apply_replacements(text, _flatten_replacements((KOREAN_PRE_REPLACEMENTS,)))

    text = _strip_combining_marks(text)
    text = unicodedata.normalize("NFKC", text)
    text = _map_mathematical_alphanumerics(text)
    text = _normalize_unicode_digits(text, drop_non_ascii_digits=normalized_language == "ko" and cleanup_non_korean)
    replacements = _flatten_replacements(REPLACEMENT_ORDER[normalized_language])
    text = _apply_replacements(text, replacements)
    text = _compose_hangul(text)
    if normalized_language == "ko" and cleanup_non_korean:
        text = _cleanup_non_korean_letters(text)
    return text


def special_en(text: str) -> str:
    """Backward-compatible English-first alias."""
    return special_text(text, preferred_language="en")


def special_ko(text: str, cleanup_non_korean: bool = True) -> str:
    """Korean-first normalization alias."""
    return special_text(text, preferred_language="ko", cleanup_non_korean=cleanup_non_korean)


if __name__ == "__main__":
    def main() -> None:
        try:
            text = input("Enter text: ")
        except EOFError:
            return
        preferred_language = input("Preferred language priority (en/ko, default en): ").strip().lower() or "en"
        cleanup_choice = input("Remove unsupported non-Korean letters? (y/N): ").strip().lower() == "y"
        print(special_text(text, preferred_language=preferred_language, cleanup_non_korean=cleanup_choice))

    main()